### PR TITLE
msm7x27a-common: Added some lost files for fix build errors.

### PR DESCRIPTION
**Pull request by Caio99BR**
Signed-off-by: Caio99BR caiooliveirafarias0@gmail.com

### CODE REVIEW

**Comment by antdking** [comment]
...........

**Comment by M1cha** [comment]
@Caio99BR looks like u forgot to add the kernel repo :)

**Comment by Caio99BR** [comment]
No, I did not forget to add the repo kernel.
I am building for e435, based from e615 repo, TeamHackLG/android_device_lge_e610

**Comment by Caio99BR** [comment]
Fix build with TeamHackLG/lge-kernel-lproj not CyanogenMod/lge-kernel-p700
Thanks!

**Pull request closed without merging**
