### PR TITLE
Set TARGET_USES_OPENGLES_FOR_SCREEN_CAPTURE to fix screenshots on P7XX

### PR DESCRIPTION
**Pull request by cr3pt**
Fix from Bart452 github.

### CODE REVIEW

**Comment by RonGokhale** [comment]
why l7 need this ?

**Comment by cr3pt** [comment]
Without this recent apps screenshots are broken. 
This commit fix apps screenshot but all's are flipped (like standard screenshot)
For correct work http://review.cyanogenmod.org/#/c/54563/ is needed.

**Comment by RonGokhale** [comment]
http://review.cyanogenmod.org/#/c/53162/ for recent app  preview fix and also this  need under p700 device boardconfig. it's device specific

**Comment by tudorsirb** [comment]
No need for this.
http://review.cyanogenmod.org/#/c/53162/ - This fixes screenshot and makes them upside down
http://vaniraosp.goo.im/#/c/8561/ - This fixes upside down screenshots

**Pull request closed without merging**
